import collections


d_info = collections.OrderedDict()

d_info["stop-L"] = {
    "name": "stop-L",
    "outputDir": "outputTree/stop-L",
    "inputFiles": [
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_01/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_02/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_03/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_04/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_05/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_06/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_07/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_08/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_09/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_10/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_11/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_12/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_13/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_14/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_15/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/run_16/unweighted_events.lhe.hepmc.root",
        
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L17.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L18.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L19.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L20.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L21.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L22.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L23.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L24.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L25.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L26.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L27.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L28.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L29.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L30.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L31.root",
        "/home/sobhatta/work/MCsamples/STOP/LEFT/L32.root",
    ],
}


d_info["stop-R"] = {
    "name": "stop-R",
    "outputDir": "outputTree/stop-R",
    "inputFiles": [
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_01/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_02/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_03/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_04/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_05/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_06/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_07/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_08/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_09/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_10/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_11/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_12/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_13/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_14/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_15/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/run_16/unweighted_events.lhe.hepmc.root",
        
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R17.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R18.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R19.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R20.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R21.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R22.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R23.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R24.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R25.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R26.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R27.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R28.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R29.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R30.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R31.root",
        "/home/sobhatta/work/MCsamples/STOP/RIGHT/R32.root",
    ],
}


d_info["Wprime-1TeV-L-lep"] = {
    "name": "Wprime-1TeV-L-lep",
    "outputDir": "outputTree/Wprime-1TeV-L-lep",
    "inputFiles": [ 
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept/Events/run_01/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept/Events/run_02/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept/Events/run_03/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept/Events/run_04/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept/Events/run_05/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept/Events/run_06/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept/Events/run_07/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept/Events/run_08/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept/Events/run_09/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept/Events/run_10/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["Wprime-1TeV-L-had"] = {
    "name": "Wprime-1TeV-L-had",
    "outputDir": "outputTree/Wprime-1TeV-L-had",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had/Events/run_01/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had/Events/run_02/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had/Events/run_03/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had/Events/run_04/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had/Events/run_05/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had/Events/run_06/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had/Events/run_07/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had/Events/run_08/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had/Events/run_09/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had/Events/run_10/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["Wprime-1TeV-R-lep"] = {
    "name": "Wprime-1TeV-R-lep",
    "outputDir": "outputTree/Wprime-1TeV-R-lep",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept/Events/run_01/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept/Events/run_02/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept/Events/run_03/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept/Events/run_04/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept/Events/run_05/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept/Events/run_06/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept/Events/run_07/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept/Events/run_08/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept/Events/run_09/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept/Events/run_10/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["Wprime-1TeV-R-had"] = {
    "name": "Wprime-1TeV-R-had",
    "outputDir": "outputTree/Wprime-1TeV-R-had",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had/Events/run_01/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had/Events/run_02/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had/Events/run_03/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had/Events/run_04/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had/Events/run_05/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had/Events/run_06/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had/Events/run_07/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had/Events/run_08/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had/Events/run_09/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had/Events/run_10/unweighted_events.lhe.hepmc.root",
    ]
}


d_info["Wprime-3TeV-L-lep"] = {
    "name": "Wprime-3TeV-L-lep",
    "outputDir": "outputTree/Wprime-3TeV-L-lep",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept_3/Events/run_01/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept_3/Events/run_02/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept_3/Events/run_03/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept_3/Events/run_04/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept_3/Events/run_05/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept_3/Events/run_06/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept_3/Events/run_07/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept_3/Events/run_08/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept_3/Events/run_09/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_lept_3/Events/run_10/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["Wprime-3TeV-L-had"] = {
    "name": "Wprime-3TeV-L-had",
    "outputDir": "outputTree/Wprime-3TeV-L-had",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had_3/Events/run_01/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had_3/Events/run_02/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had_3/Events/run_03/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had_3/Events/run_04/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had_3/Events/run_05/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had_3/Events/run_06/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had_3/Events/run_07/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had_3/Events/run_08/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had_3/Events/run_09/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_left_had_3/Events/run_10/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["Wprime-3TeV-R-lep"] = {
    "name": "Wprime-3TeV-R-lep",
    "outputDir": "outputTree/Wprime-3TeV-R-lep",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept_3/Events/run_01/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept_3/Events/run_02/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept_3/Events/run_03/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept_3/Events/run_04/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept_3/Events/run_05/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept_3/Events/run_06/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept_3/Events/run_07/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept_3/Events/run_08/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept_3/Events/run_09/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_lept_3/Events/run_10/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["Wprime-3TeV-R-had"] = {
    "name": "Wprime-3TeV-R-had",
    "outputDir": "outputTree/Wprime-3TeV-R-had",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had_3/Events/run_01/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had_3/Events/run_02/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had_3/Events/run_03/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had_3/Events/run_04/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had_3/Events/run_05/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had_3/Events/run_06/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had_3/Events/run_07/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had_3/Events/run_08/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had_3/Events/run_09/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/wprime_right_had_3/Events/run_10/unweighted_events.lhe.hepmc.root",
    ]
}


d_info["ttbar-tj"] = {
    "name": "ttbar-tj",
    "outputDir": "outputTree/ttbar-tj",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_01_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_02_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_03_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_04_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_05_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_06_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_07_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_08_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_09_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_10_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_11_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_12_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_13_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_14_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_15_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_16_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_17_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_18_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_19_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar/Events/run_20_decayed_1/unweighted_events.lhe.hepmc.root",
        
        "/home/sobhatta/work/MCsamples/TTBAR/TJ/run_01_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TJ/run_02_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TJ/run_03_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TJ/run_04_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TJ/run_05_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TJ/run_06_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TJ/run_07_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TJ/run_08_decayed_1/unweighted_events.lhe.hepmc.root",
    ]
}


d_info["ttbar-tbarj"] = {
    "name": "ttbar-tbarj",
    "outputDir": "outputTree/ttbar-tbarj",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_01_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_02_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_03_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_04_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_05_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_06_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_07_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_08_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_09_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_10_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_11_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_12_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_13_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_14_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_15_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_16_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_17_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_18_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_19_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_6_7/ttbar2/Events/run_20_decayed_1/unweighted_events.lhe.hepmc.root",
        
        "/home/sobhatta/work/MCsamples/TTBAR/TBARJ/run_09_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TBARJ/run_10_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TBARJ/run_11_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TBARJ/run_12_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TBARJ/run_13_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TBARJ/run_14_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TBARJ/run_15_decayed_1/unweighted_events.lhe.hepmc.root",
        "/home/sobhatta/work/MCsamples/TTBAR/TBARJ/run_16_decayed_1/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["W-lep"] = {
    "name": "W-lep",
    "outputDir": "outputTree/W-lep",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_01_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_02_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_03_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_04_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_05_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_06_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_07_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_08_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_09_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_10_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_11_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_12_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_13_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_14_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_15_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_16_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_17_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_18_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_19_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_20_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_21_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_22_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_23_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_24_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_25_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_26_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_27_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_28_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_29_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_30_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_31_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_32_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_33_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_34_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_35_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_36_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_37_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_38_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_39_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_40_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_41_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_42_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_43_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_44_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_45_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_46_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_47_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_48_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_49_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_50_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_51_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_52_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_53_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_54_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_55_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_56_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_57_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_58_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_59_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_60_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_61_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_62_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_63_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_64_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_65_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_66_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_67_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_68_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_69_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_70_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_71_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_72_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_73_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_74_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_75_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_76_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_77_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_78_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_79_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_80_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_81_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_82_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_83_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_84_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_85_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_86_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_87_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_88_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets/Events/run_89_decayed_1/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["W-lep_pt10to100"] = {
    "name": "W-lep_pt10to100",
    "outputDir": "outputTree/W-lep_pt10to100",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_10_100/run_02_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_10_100/run_03_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_10_100/run_04_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_10_100/run_05_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_10_100/run_06_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_10_100/run_07_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_10_100/run_08_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_10_100/run_09_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_10_100/run_10_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_10_100/run_11_decayed_1/unweighted_events.lhe.hepmc.root",
    ]
}


d_info["W-lep_pt100to200"] = {
    "name": "W-lep_pt100to200",
    "outputDir": "outputTree/W-lep_pt100to200",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_100_200/run_01_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_100_200/run_02_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_100_200/run_03_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_100_200/run_04_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_100_200/run_05_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_100_200/run_06_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_100_200/run_07_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_100_200/run_08_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_100_200/run_09_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_100_200/run_10_decayed_1/unweighted_events.lhe.hepmc.root",
    ]
}


d_info["W-lep_pt200to400"] = {
    "name": "W-lep_pt200to400",
    "outputDir": "outputTree/W-lep_pt200to400",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_200_400/run_01_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_200_400/run_02_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_200_400/run_03_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_200_400/run_04_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_200_400/run_05_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_200_400/run_06_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_200_400/run_07_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_200_400/run_08_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_200_400/run_09_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_leptonic_jets_10_100/Events/Pt_200_400/run_10_decayed_1/unweighted_events.lhe.hepmc.root",
    ]
}


d_info["W-had"] = {
    "name": "W-had",
    "outputDir": "outputTree/W-had",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_01_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_02_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_03_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_04_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_05_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_06_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_07_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_08_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_09_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_10_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_11_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_12_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_13_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_14_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_15_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_16_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_17_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_18_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_19_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_20_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_21_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_22_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_23_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_24_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_25_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_26_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_27_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_28_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_29_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_30_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_31_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_32_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_33_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_34_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_35_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_36_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_37_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_38_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_39_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_40_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_41_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_42_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_43_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/w_jets/Events/run_44_decayed_1/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["Z-lep"] = {
    "name": "Z-lep",
    "outputDir": "outputTree/Z-lep",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_01_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_02_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_03_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_04_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_05_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_06_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_07_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_08_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_09_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_10_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_11_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_12_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_13_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_14_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_15_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_16_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_17_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_18_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_19_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_20_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_21_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_22_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_23_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_24_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_25_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_26_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_27_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_28_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_29_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_30_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_31_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_32_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_33_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_34_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_35_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_36_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_37_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_38_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_39_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_40_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_leptonic_jets/Events/run_41_decayed_1/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["Z-had"] = {
    "name": "Z-had",
    "outputDir": "outputTree/Z-had",
    "inputFiles": [
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_01_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_02_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_03_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_04_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_05_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_06_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_07_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_08_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_09_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_10_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_11_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_12_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_13_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_14_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_15_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_16_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_17_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_18_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_19_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_20_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_21_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_22_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_23_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_24_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_25_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_26_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_27_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_28_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_29_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_30_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_31_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_32_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_33_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_34_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_35_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_36_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_37_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_38_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_39_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_40_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_41_decayed_1/unweighted_events.lhe.hepmc.root",
        "/grid_mnt/t3storage3/arvind/MG5_aMC_v2_9_1_2/z_jets/Events/run_42_decayed_1/unweighted_events.lhe.hepmc.root",
    ],
}


d_info["qcd"] = {
    "name": "qcd",
    "outputDir": "outputTree/qcd",
    "inputFiles": [
        "/home/sobhatta/work/MCsamples/QCD/0/hepmc.fifo.root",
        "/home/sobhatta/work/MCsamples/QCD/1/hepmc.fifo.root",
        "/home/sobhatta/work/MCsamples/QCD/2/hepmc.fifo.root",
        "/home/sobhatta/work/MCsamples/QCD/3/hepmc.fifo.root",
        "/home/sobhatta/work/MCsamples/QCD/4/hepmc.fifo.root",
        "/home/sobhatta/work/MCsamples/QCD/5/hepmc.fifo.root",
        "/home/sobhatta/work/MCsamples/QCD/6/hepmc.fifo.root",
        "/home/sobhatta/work/MCsamples/QCD/7/hepmc.fifo.root",
    ]
}

